### PR TITLE
rewrite entire program in Rust

### PR DESCRIPTION
**Pull request by zacharyburnett**
preliminary refactor for most functionality. Example output running on `examples/example_1.yml`:
```
> cargo run examples/example_1.yml
warning: `packetraven` (bin "packetraven") generated 21 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 7.36s
     Running `target/debug/packetraven ./examples/example_1.yaml`
[2023-05-09T18:48:02Z INFO  packetraven] starting
[2023-05-09T18:48:02Z INFO  packetraven] retrieving packets
[2023-05-09T18:48:02Z INFO  packetraven] reading text file http://bpp.umd.edu/archives/Launches/NS-111_2022_07_31/APRS/W3EAX-11%20raw.txt
[2023-05-09T18:48:02Z INFO  packetraven] reading text file http://bpp.umd.edu/archives/Launches/NS-111_2022_07_31/APRS/W3EAX-8%20raw.txt
[2023-05-09T18:48:02Z INFO  packetraven] listening for packets every 10 s from 2 source(s)
[2023-05-09T18:48:03Z INFO  packetraven] W3EAX-8 - location #51 (-76.9995, 39.44566666666666, 2431.0848 m); packet time is 2023-05-09 11:49:33 -04:00 (150 s since the previous packet); traveled 1090.509392496289 m (7.270062616641926 m/s) over the ground and -974.4456 m (-6.496304 m/s) vertically
[2023-05-09T18:48:03Z INFO  packetraven] W3EAX-8 - altitude: 2431.0848 m; avg. ascent rate: 5.874808611842108 m/s; avg. descent rate: -11.796273462788688 m/s; avg. ground speed: 15.040322350263034 m/s; avg. packet interval: 110.32 s
[2023-05-09T18:48:03Z INFO  packetraven] W3EAX-11 - location #107 (-77.05916666666667, 39.420833333333334, 517.8552000000001 m); packet time is 2023-05-09 14:48:03.089828883 -04:00 (0 s since the previous packet); traveled 18.503920416846587 m (inf m/s) over the ground and -309.06719999999996 m (-inf m/s) vertically
[2023-05-09T18:48:03Z INFO  packetraven] W3EAX-11 - altitude: 517.8552000000001 m; avg. ascent rate: inf m/s; avg. descent rate: -inf m/s; avg. ground speed: inf m/s; avg. packet interval: 0 s
[2023-05-09T18:48:03Z INFO  packetraven] received 158 new packets
[2023-05-09T18:48:13Z INFO  packetraven] received 0 new packets
```

TODO:
- file output
  - [ ] log
  - [ ] packet locations (GeoJSON)
  - [ ] prediction
- plotting
  - [x] altitude / time
  - [x] ascent rate / time
  - [x] ground speed / altitude
  - [ ] press key to color packets by source w/ legend
- [x] ~GUI~ TUI
- ~PostGres support (read and send)~ relegated to an optional crate feature
  - [x] query
  - [ ] ~post~
- [ ] APRS-IS support (read and send)
- [ ] track time interpolation (useful for plotting)
- SondeHub support
  - [x] query
  - [ ] post
- [ ] indication of key mapping (currently `Esc` or `q` to quit, `Spacebar` or `r` to refresh, `Tab` or `->` to move to the next tab, and `Shift+Tab` or `<-` to move to the previous tab)
- [x] fix log scrolling when pressing up and down keys

### CODE REVIEW

**Comment by zacharyburnett** [comment]
> YES

lol I got sick of Python packaging

still got a whole lot of TODOs though

**Comment by zacharyburnett** [comment]
built a TUI:
image
image
@michaelshipman as I don't have a Windows machine, would you mind testing it with `cargo run examples/example_1.yaml`?

**Comment by zacharyburnett** [comment]
added a plot 
image

**Comment by michaelshipman** [comment]
Yep still around! I'll try to give it a shot this weekend.

**Comment by zacharyburnett** [comment]
the compiled binary for Windows is here: https://github.com/UMDBPP/PacketRaven/suites/13162348747/artifacts/715910247

It *should* work with the first example:
```
packetraven.exe examples/example_1.yaml
```

**Comment by zacharyburnett** [comment]
TUI tested on Windows; merging after other tests pass

**Pull request merged**
